// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EntryType int32

const (
	EntryType_file EntryType = 0
	EntryType_dir  EntryType = 1
)

var EntryType_name = map[int32]string{
	0: "file",
	1: "dir",
}

var EntryType_value = map[string]int32{
	"file": 0,
	"dir":  1,
}

func (x EntryType) String() string {
	return proto.EnumName(EntryType_name, int32(x))
}

func (EntryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

type Error struct {
	// Types that are valid to be assigned to Err:
	//	*Error_Errno
	//	*Error_Msg
	Err                  isError_Err `protobuf_oneof:"err"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

type isError_Err interface {
	isError_Err()
}

type Error_Errno struct {
	Errno uint32 `protobuf:"varint,1,opt,name=errno,proto3,oneof"`
}

type Error_Msg struct {
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3,oneof"`
}

func (*Error_Errno) isError_Err() {}

func (*Error_Msg) isError_Err() {}

func (m *Error) GetErr() isError_Err {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *Error) GetErrno() uint32 {
	if x, ok := m.GetErr().(*Error_Errno); ok {
		return x.Errno
	}
	return 0
}

func (m *Error) GetMsg() string {
	if x, ok := m.GetErr().(*Error_Msg); ok {
		return x.Msg
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Error) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Error_Errno)(nil),
		(*Error_Msg)(nil),
	}
}

type Attr struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mode                 int32                `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Size                 int64                `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Type                 EntryType            `protobuf:"varint,4,opt,name=type,proto3,enum=rpc.EntryType" json:"type,omitempty"`
	AccessTime           *timestamp.Timestamp `protobuf:"bytes,5,opt,name=accessTime,proto3" json:"accessTime,omitempty"`
	ModifyTime           *timestamp.Timestamp `protobuf:"bytes,6,opt,name=modifyTime,proto3" json:"modifyTime,omitempty"`
	ChangeTime           *timestamp.Timestamp `protobuf:"bytes,7,opt,name=changeTime,proto3" json:"changeTime,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Attr) Reset()         { *m = Attr{} }
func (m *Attr) String() string { return proto.CompactTextString(m) }
func (*Attr) ProtoMessage()    {}
func (*Attr) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{1}
}

func (m *Attr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attr.Unmarshal(m, b)
}
func (m *Attr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attr.Marshal(b, m, deterministic)
}
func (m *Attr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attr.Merge(m, src)
}
func (m *Attr) XXX_Size() int {
	return xxx_messageInfo_Attr.Size(m)
}
func (m *Attr) XXX_DiscardUnknown() {
	xxx_messageInfo_Attr.DiscardUnknown(m)
}

var xxx_messageInfo_Attr proto.InternalMessageInfo

func (m *Attr) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Attr) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *Attr) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Attr) GetType() EntryType {
	if m != nil {
		return m.Type
	}
	return EntryType_file
}

func (m *Attr) GetAccessTime() *timestamp.Timestamp {
	if m != nil {
		return m.AccessTime
	}
	return nil
}

func (m *Attr) GetModifyTime() *timestamp.Timestamp {
	if m != nil {
		return m.ModifyTime
	}
	return nil
}

func (m *Attr) GetChangeTime() *timestamp.Timestamp {
	if m != nil {
		return m.ChangeTime
	}
	return nil
}

func (m *Attr) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

type ReadDirRequest struct {
	DirPath              string   `protobuf:"bytes,1,opt,name=dirPath,proto3" json:"dirPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadDirRequest) Reset()         { *m = ReadDirRequest{} }
func (m *ReadDirRequest) String() string { return proto.CompactTextString(m) }
func (*ReadDirRequest) ProtoMessage()    {}
func (*ReadDirRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{2}
}

func (m *ReadDirRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadDirRequest.Unmarshal(m, b)
}
func (m *ReadDirRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadDirRequest.Marshal(b, m, deterministic)
}
func (m *ReadDirRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadDirRequest.Merge(m, src)
}
func (m *ReadDirRequest) XXX_Size() int {
	return xxx_messageInfo_ReadDirRequest.Size(m)
}
func (m *ReadDirRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadDirRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadDirRequest proto.InternalMessageInfo

func (m *ReadDirRequest) GetDirPath() string {
	if m != nil {
		return m.DirPath
	}
	return ""
}

type ReadDirResponse struct {
	DirEntries           []*ReadDirResponse_DirEntry `protobuf:"bytes,1,rep,name=dirEntries,proto3" json:"dirEntries,omitempty"`
	Error                *Error                      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ReadDirResponse) Reset()         { *m = ReadDirResponse{} }
func (m *ReadDirResponse) String() string { return proto.CompactTextString(m) }
func (*ReadDirResponse) ProtoMessage()    {}
func (*ReadDirResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{3}
}

func (m *ReadDirResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadDirResponse.Unmarshal(m, b)
}
func (m *ReadDirResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadDirResponse.Marshal(b, m, deterministic)
}
func (m *ReadDirResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadDirResponse.Merge(m, src)
}
func (m *ReadDirResponse) XXX_Size() int {
	return xxx_messageInfo_ReadDirResponse.Size(m)
}
func (m *ReadDirResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadDirResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadDirResponse proto.InternalMessageInfo

func (m *ReadDirResponse) GetDirEntries() []*ReadDirResponse_DirEntry {
	if m != nil {
		return m.DirEntries
	}
	return nil
}

func (m *ReadDirResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ReadDirResponse_DirEntry struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 EntryType `protobuf:"varint,2,opt,name=type,proto3,enum=rpc.EntryType" json:"type,omitempty"`
	Mode                 uint32    `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReadDirResponse_DirEntry) Reset()         { *m = ReadDirResponse_DirEntry{} }
func (m *ReadDirResponse_DirEntry) String() string { return proto.CompactTextString(m) }
func (*ReadDirResponse_DirEntry) ProtoMessage()    {}
func (*ReadDirResponse_DirEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{3, 0}
}

func (m *ReadDirResponse_DirEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadDirResponse_DirEntry.Unmarshal(m, b)
}
func (m *ReadDirResponse_DirEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadDirResponse_DirEntry.Marshal(b, m, deterministic)
}
func (m *ReadDirResponse_DirEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadDirResponse_DirEntry.Merge(m, src)
}
func (m *ReadDirResponse_DirEntry) XXX_Size() int {
	return xxx_messageInfo_ReadDirResponse_DirEntry.Size(m)
}
func (m *ReadDirResponse_DirEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadDirResponse_DirEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ReadDirResponse_DirEntry proto.InternalMessageInfo

func (m *ReadDirResponse_DirEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReadDirResponse_DirEntry) GetType() EntryType {
	if m != nil {
		return m.Type
	}
	return EntryType_file
}

func (m *ReadDirResponse_DirEntry) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

type LookupRequest struct {
	DirPath              string   `protobuf:"bytes,1,opt,name=dirPath,proto3" json:"dirPath,omitempty"`
	Filename             string   `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookupRequest) Reset()         { *m = LookupRequest{} }
func (m *LookupRequest) String() string { return proto.CompactTextString(m) }
func (*LookupRequest) ProtoMessage()    {}
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{4}
}

func (m *LookupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupRequest.Unmarshal(m, b)
}
func (m *LookupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupRequest.Marshal(b, m, deterministic)
}
func (m *LookupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupRequest.Merge(m, src)
}
func (m *LookupRequest) XXX_Size() int {
	return xxx_messageInfo_LookupRequest.Size(m)
}
func (m *LookupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LookupRequest proto.InternalMessageInfo

func (m *LookupRequest) GetDirPath() string {
	if m != nil {
		return m.DirPath
	}
	return ""
}

func (m *LookupRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type LookupResponse struct {
	// Types that are valid to be assigned to Result:
	//	*LookupResponse_Attr
	//	*LookupResponse_Error
	Result               isLookupResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *LookupResponse) Reset()         { *m = LookupResponse{} }
func (m *LookupResponse) String() string { return proto.CompactTextString(m) }
func (*LookupResponse) ProtoMessage()    {}
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{5}
}

func (m *LookupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupResponse.Unmarshal(m, b)
}
func (m *LookupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupResponse.Marshal(b, m, deterministic)
}
func (m *LookupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupResponse.Merge(m, src)
}
func (m *LookupResponse) XXX_Size() int {
	return xxx_messageInfo_LookupResponse.Size(m)
}
func (m *LookupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LookupResponse proto.InternalMessageInfo

type isLookupResponse_Result interface {
	isLookupResponse_Result()
}

type LookupResponse_Attr struct {
	Attr *Attr `protobuf:"bytes,1,opt,name=attr,proto3,oneof"`
}

type LookupResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*LookupResponse_Attr) isLookupResponse_Result() {}

func (*LookupResponse_Error) isLookupResponse_Result() {}

func (m *LookupResponse) GetResult() isLookupResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *LookupResponse) GetAttr() *Attr {
	if x, ok := m.GetResult().(*LookupResponse_Attr); ok {
		return x.Attr
	}
	return nil
}

func (m *LookupResponse) GetError() *Error {
	if x, ok := m.GetResult().(*LookupResponse_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LookupResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LookupResponse_Attr)(nil),
		(*LookupResponse_Error)(nil),
	}
}

type MkdirRequest struct {
	DirPath              string   `protobuf:"bytes,1,opt,name=dirPath,proto3" json:"dirPath,omitempty"`
	NewName              string   `protobuf:"bytes,2,opt,name=newName,proto3" json:"newName,omitempty"`
	Mode                 uint32   `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MkdirRequest) Reset()         { *m = MkdirRequest{} }
func (m *MkdirRequest) String() string { return proto.CompactTextString(m) }
func (*MkdirRequest) ProtoMessage()    {}
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{6}
}

func (m *MkdirRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MkdirRequest.Unmarshal(m, b)
}
func (m *MkdirRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MkdirRequest.Marshal(b, m, deterministic)
}
func (m *MkdirRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MkdirRequest.Merge(m, src)
}
func (m *MkdirRequest) XXX_Size() int {
	return xxx_messageInfo_MkdirRequest.Size(m)
}
func (m *MkdirRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MkdirRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MkdirRequest proto.InternalMessageInfo

func (m *MkdirRequest) GetDirPath() string {
	if m != nil {
		return m.DirPath
	}
	return ""
}

func (m *MkdirRequest) GetNewName() string {
	if m != nil {
		return m.NewName
	}
	return ""
}

func (m *MkdirRequest) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

type MkdirResponse struct {
	// Types that are valid to be assigned to Result:
	//	*MkdirResponse_Attr
	//	*MkdirResponse_Error
	Result               isMkdirResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *MkdirResponse) Reset()         { *m = MkdirResponse{} }
func (m *MkdirResponse) String() string { return proto.CompactTextString(m) }
func (*MkdirResponse) ProtoMessage()    {}
func (*MkdirResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{7}
}

func (m *MkdirResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MkdirResponse.Unmarshal(m, b)
}
func (m *MkdirResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MkdirResponse.Marshal(b, m, deterministic)
}
func (m *MkdirResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MkdirResponse.Merge(m, src)
}
func (m *MkdirResponse) XXX_Size() int {
	return xxx_messageInfo_MkdirResponse.Size(m)
}
func (m *MkdirResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MkdirResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MkdirResponse proto.InternalMessageInfo

type isMkdirResponse_Result interface {
	isMkdirResponse_Result()
}

type MkdirResponse_Attr struct {
	Attr *Attr `protobuf:"bytes,1,opt,name=attr,proto3,oneof"`
}

type MkdirResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*MkdirResponse_Attr) isMkdirResponse_Result() {}

func (*MkdirResponse_Error) isMkdirResponse_Result() {}

func (m *MkdirResponse) GetResult() isMkdirResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *MkdirResponse) GetAttr() *Attr {
	if x, ok := m.GetResult().(*MkdirResponse_Attr); ok {
		return x.Attr
	}
	return nil
}

func (m *MkdirResponse) GetError() *Error {
	if x, ok := m.GetResult().(*MkdirResponse_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MkdirResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MkdirResponse_Attr)(nil),
		(*MkdirResponse_Error)(nil),
	}
}

type CreateFileRequest struct {
	DirPath              string   `protobuf:"bytes,1,opt,name=dirPath,proto3" json:"dirPath,omitempty"`
	Filename             string   `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Mode                 uint32   `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFileRequest) Reset()         { *m = CreateFileRequest{} }
func (m *CreateFileRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFileRequest) ProtoMessage()    {}
func (*CreateFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{8}
}

func (m *CreateFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFileRequest.Unmarshal(m, b)
}
func (m *CreateFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFileRequest.Marshal(b, m, deterministic)
}
func (m *CreateFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFileRequest.Merge(m, src)
}
func (m *CreateFileRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFileRequest.Size(m)
}
func (m *CreateFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFileRequest proto.InternalMessageInfo

func (m *CreateFileRequest) GetDirPath() string {
	if m != nil {
		return m.DirPath
	}
	return ""
}

func (m *CreateFileRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *CreateFileRequest) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

type CreateFileResponse struct {
	// Types that are valid to be assigned to Result:
	//	*CreateFileResponse_Attr
	//	*CreateFileResponse_Error
	Result               isCreateFileResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CreateFileResponse) Reset()         { *m = CreateFileResponse{} }
func (m *CreateFileResponse) String() string { return proto.CompactTextString(m) }
func (*CreateFileResponse) ProtoMessage()    {}
func (*CreateFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{9}
}

func (m *CreateFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFileResponse.Unmarshal(m, b)
}
func (m *CreateFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFileResponse.Marshal(b, m, deterministic)
}
func (m *CreateFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFileResponse.Merge(m, src)
}
func (m *CreateFileResponse) XXX_Size() int {
	return xxx_messageInfo_CreateFileResponse.Size(m)
}
func (m *CreateFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFileResponse proto.InternalMessageInfo

type isCreateFileResponse_Result interface {
	isCreateFileResponse_Result()
}

type CreateFileResponse_Attr struct {
	Attr *Attr `protobuf:"bytes,1,opt,name=attr,proto3,oneof"`
}

type CreateFileResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*CreateFileResponse_Attr) isCreateFileResponse_Result() {}

func (*CreateFileResponse_Error) isCreateFileResponse_Result() {}

func (m *CreateFileResponse) GetResult() isCreateFileResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CreateFileResponse) GetAttr() *Attr {
	if x, ok := m.GetResult().(*CreateFileResponse_Attr); ok {
		return x.Attr
	}
	return nil
}

func (m *CreateFileResponse) GetError() *Error {
	if x, ok := m.GetResult().(*CreateFileResponse_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CreateFileResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CreateFileResponse_Attr)(nil),
		(*CreateFileResponse_Error)(nil),
	}
}

type UnlinkRequest struct {
	DirPath              string   `protobuf:"bytes,1,opt,name=dirPath,proto3" json:"dirPath,omitempty"`
	Filename             string   `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlinkRequest) Reset()         { *m = UnlinkRequest{} }
func (m *UnlinkRequest) String() string { return proto.CompactTextString(m) }
func (*UnlinkRequest) ProtoMessage()    {}
func (*UnlinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{10}
}

func (m *UnlinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlinkRequest.Unmarshal(m, b)
}
func (m *UnlinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlinkRequest.Marshal(b, m, deterministic)
}
func (m *UnlinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlinkRequest.Merge(m, src)
}
func (m *UnlinkRequest) XXX_Size() int {
	return xxx_messageInfo_UnlinkRequest.Size(m)
}
func (m *UnlinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnlinkRequest proto.InternalMessageInfo

func (m *UnlinkRequest) GetDirPath() string {
	if m != nil {
		return m.DirPath
	}
	return ""
}

func (m *UnlinkRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type UnlinkResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlinkResponse) Reset()         { *m = UnlinkResponse{} }
func (m *UnlinkResponse) String() string { return proto.CompactTextString(m) }
func (*UnlinkResponse) ProtoMessage()    {}
func (*UnlinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{11}
}

func (m *UnlinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlinkResponse.Unmarshal(m, b)
}
func (m *UnlinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlinkResponse.Marshal(b, m, deterministic)
}
func (m *UnlinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlinkResponse.Merge(m, src)
}
func (m *UnlinkResponse) XXX_Size() int {
	return xxx_messageInfo_UnlinkResponse.Size(m)
}
func (m *UnlinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnlinkResponse proto.InternalMessageInfo

func (m *UnlinkResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type RmDirRequest struct {
	DirPath              string   `protobuf:"bytes,1,opt,name=dirPath,proto3" json:"dirPath,omitempty"`
	RmName               string   `protobuf:"bytes,2,opt,name=rmName,proto3" json:"rmName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RmDirRequest) Reset()         { *m = RmDirRequest{} }
func (m *RmDirRequest) String() string { return proto.CompactTextString(m) }
func (*RmDirRequest) ProtoMessage()    {}
func (*RmDirRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{12}
}

func (m *RmDirRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RmDirRequest.Unmarshal(m, b)
}
func (m *RmDirRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RmDirRequest.Marshal(b, m, deterministic)
}
func (m *RmDirRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RmDirRequest.Merge(m, src)
}
func (m *RmDirRequest) XXX_Size() int {
	return xxx_messageInfo_RmDirRequest.Size(m)
}
func (m *RmDirRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RmDirRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RmDirRequest proto.InternalMessageInfo

func (m *RmDirRequest) GetDirPath() string {
	if m != nil {
		return m.DirPath
	}
	return ""
}

func (m *RmDirRequest) GetRmName() string {
	if m != nil {
		return m.RmName
	}
	return ""
}

type RmDirResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RmDirResponse) Reset()         { *m = RmDirResponse{} }
func (m *RmDirResponse) String() string { return proto.CompactTextString(m) }
func (*RmDirResponse) ProtoMessage()    {}
func (*RmDirResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{13}
}

func (m *RmDirResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RmDirResponse.Unmarshal(m, b)
}
func (m *RmDirResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RmDirResponse.Marshal(b, m, deterministic)
}
func (m *RmDirResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RmDirResponse.Merge(m, src)
}
func (m *RmDirResponse) XXX_Size() int {
	return xxx_messageInfo_RmDirResponse.Size(m)
}
func (m *RmDirResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RmDirResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RmDirResponse proto.InternalMessageInfo

func (m *RmDirResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type RenameRequest struct {
	DirPath              string   `protobuf:"bytes,1,opt,name=dirPath,proto3" json:"dirPath,omitempty"`
	OldName              string   `protobuf:"bytes,2,opt,name=oldName,proto3" json:"oldName,omitempty"`
	NewDirPath           string   `protobuf:"bytes,3,opt,name=newDirPath,proto3" json:"newDirPath,omitempty"`
	NewName              string   `protobuf:"bytes,4,opt,name=newName,proto3" json:"newName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenameRequest) Reset()         { *m = RenameRequest{} }
func (m *RenameRequest) String() string { return proto.CompactTextString(m) }
func (*RenameRequest) ProtoMessage()    {}
func (*RenameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{14}
}

func (m *RenameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenameRequest.Unmarshal(m, b)
}
func (m *RenameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenameRequest.Marshal(b, m, deterministic)
}
func (m *RenameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenameRequest.Merge(m, src)
}
func (m *RenameRequest) XXX_Size() int {
	return xxx_messageInfo_RenameRequest.Size(m)
}
func (m *RenameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RenameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RenameRequest proto.InternalMessageInfo

func (m *RenameRequest) GetDirPath() string {
	if m != nil {
		return m.DirPath
	}
	return ""
}

func (m *RenameRequest) GetOldName() string {
	if m != nil {
		return m.OldName
	}
	return ""
}

func (m *RenameRequest) GetNewDirPath() string {
	if m != nil {
		return m.NewDirPath
	}
	return ""
}

func (m *RenameRequest) GetNewName() string {
	if m != nil {
		return m.NewName
	}
	return ""
}

type RenameResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenameResponse) Reset()         { *m = RenameResponse{} }
func (m *RenameResponse) String() string { return proto.CompactTextString(m) }
func (*RenameResponse) ProtoMessage()    {}
func (*RenameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{15}
}

func (m *RenameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenameResponse.Unmarshal(m, b)
}
func (m *RenameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenameResponse.Marshal(b, m, deterministic)
}
func (m *RenameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenameResponse.Merge(m, src)
}
func (m *RenameResponse) XXX_Size() int {
	return xxx_messageInfo_RenameResponse.Size(m)
}
func (m *RenameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RenameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RenameResponse proto.InternalMessageInfo

func (m *RenameResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type OpenFileRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenFileRequest) Reset()         { *m = OpenFileRequest{} }
func (m *OpenFileRequest) String() string { return proto.CompactTextString(m) }
func (*OpenFileRequest) ProtoMessage()    {}
func (*OpenFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{16}
}

func (m *OpenFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenFileRequest.Unmarshal(m, b)
}
func (m *OpenFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenFileRequest.Marshal(b, m, deterministic)
}
func (m *OpenFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenFileRequest.Merge(m, src)
}
func (m *OpenFileRequest) XXX_Size() int {
	return xxx_messageInfo_OpenFileRequest.Size(m)
}
func (m *OpenFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenFileRequest proto.InternalMessageInfo

func (m *OpenFileRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type OpenFileResponse struct {
	// Types that are valid to be assigned to Result:
	//	*OpenFileResponse_Attr
	//	*OpenFileResponse_Error
	Result               isOpenFileResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *OpenFileResponse) Reset()         { *m = OpenFileResponse{} }
func (m *OpenFileResponse) String() string { return proto.CompactTextString(m) }
func (*OpenFileResponse) ProtoMessage()    {}
func (*OpenFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{17}
}

func (m *OpenFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenFileResponse.Unmarshal(m, b)
}
func (m *OpenFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenFileResponse.Marshal(b, m, deterministic)
}
func (m *OpenFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenFileResponse.Merge(m, src)
}
func (m *OpenFileResponse) XXX_Size() int {
	return xxx_messageInfo_OpenFileResponse.Size(m)
}
func (m *OpenFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OpenFileResponse proto.InternalMessageInfo

type isOpenFileResponse_Result interface {
	isOpenFileResponse_Result()
}

type OpenFileResponse_Attr struct {
	Attr *Attr `protobuf:"bytes,1,opt,name=attr,proto3,oneof"`
}

type OpenFileResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*OpenFileResponse_Attr) isOpenFileResponse_Result() {}

func (*OpenFileResponse_Error) isOpenFileResponse_Result() {}

func (m *OpenFileResponse) GetResult() isOpenFileResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *OpenFileResponse) GetAttr() *Attr {
	if x, ok := m.GetResult().(*OpenFileResponse_Attr); ok {
		return x.Attr
	}
	return nil
}

func (m *OpenFileResponse) GetError() *Error {
	if x, ok := m.GetResult().(*OpenFileResponse_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*OpenFileResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*OpenFileResponse_Attr)(nil),
		(*OpenFileResponse_Error)(nil),
	}
}

type AllocateRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset               uint64   `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Size                 uint64   `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllocateRequest) Reset()         { *m = AllocateRequest{} }
func (m *AllocateRequest) String() string { return proto.CompactTextString(m) }
func (*AllocateRequest) ProtoMessage()    {}
func (*AllocateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{18}
}

func (m *AllocateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllocateRequest.Unmarshal(m, b)
}
func (m *AllocateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllocateRequest.Marshal(b, m, deterministic)
}
func (m *AllocateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllocateRequest.Merge(m, src)
}
func (m *AllocateRequest) XXX_Size() int {
	return xxx_messageInfo_AllocateRequest.Size(m)
}
func (m *AllocateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllocateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllocateRequest proto.InternalMessageInfo

func (m *AllocateRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *AllocateRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *AllocateRequest) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type AllocateResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllocateResponse) Reset()         { *m = AllocateResponse{} }
func (m *AllocateResponse) String() string { return proto.CompactTextString(m) }
func (*AllocateResponse) ProtoMessage()    {}
func (*AllocateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{19}
}

func (m *AllocateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllocateResponse.Unmarshal(m, b)
}
func (m *AllocateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllocateResponse.Marshal(b, m, deterministic)
}
func (m *AllocateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllocateResponse.Merge(m, src)
}
func (m *AllocateResponse) XXX_Size() int {
	return xxx_messageInfo_AllocateResponse.Size(m)
}
func (m *AllocateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllocateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllocateResponse proto.InternalMessageInfo

func (m *AllocateResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ReadFileRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Size                 uint64   `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadFileRequest) Reset()         { *m = ReadFileRequest{} }
func (m *ReadFileRequest) String() string { return proto.CompactTextString(m) }
func (*ReadFileRequest) ProtoMessage()    {}
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{20}
}

func (m *ReadFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadFileRequest.Unmarshal(m, b)
}
func (m *ReadFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadFileRequest.Marshal(b, m, deterministic)
}
func (m *ReadFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadFileRequest.Merge(m, src)
}
func (m *ReadFileRequest) XXX_Size() int {
	return xxx_messageInfo_ReadFileRequest.Size(m)
}
func (m *ReadFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadFileRequest proto.InternalMessageInfo

func (m *ReadFileRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ReadFileRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ReadFileRequest) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type ReadFileResponse struct {
	// Types that are valid to be assigned to Result:
	//	*ReadFileResponse_Data
	//	*ReadFileResponse_Error
	Result               isReadFileResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ReadFileResponse) Reset()         { *m = ReadFileResponse{} }
func (m *ReadFileResponse) String() string { return proto.CompactTextString(m) }
func (*ReadFileResponse) ProtoMessage()    {}
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{21}
}

func (m *ReadFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadFileResponse.Unmarshal(m, b)
}
func (m *ReadFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadFileResponse.Marshal(b, m, deterministic)
}
func (m *ReadFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadFileResponse.Merge(m, src)
}
func (m *ReadFileResponse) XXX_Size() int {
	return xxx_messageInfo_ReadFileResponse.Size(m)
}
func (m *ReadFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadFileResponse proto.InternalMessageInfo

type isReadFileResponse_Result interface {
	isReadFileResponse_Result()
}

type ReadFileResponse_Data struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type ReadFileResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ReadFileResponse_Data) isReadFileResponse_Result() {}

func (*ReadFileResponse_Error) isReadFileResponse_Result() {}

func (m *ReadFileResponse) GetResult() isReadFileResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ReadFileResponse) GetData() []byte {
	if x, ok := m.GetResult().(*ReadFileResponse_Data); ok {
		return x.Data
	}
	return nil
}

func (m *ReadFileResponse) GetError() *Error {
	if x, ok := m.GetResult().(*ReadFileResponse_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ReadFileResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ReadFileResponse_Data)(nil),
		(*ReadFileResponse_Error)(nil),
	}
}

type WriteFileRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteFileRequest) Reset()         { *m = WriteFileRequest{} }
func (m *WriteFileRequest) String() string { return proto.CompactTextString(m) }
func (*WriteFileRequest) ProtoMessage()    {}
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{22}
}

func (m *WriteFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteFileRequest.Unmarshal(m, b)
}
func (m *WriteFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteFileRequest.Marshal(b, m, deterministic)
}
func (m *WriteFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteFileRequest.Merge(m, src)
}
func (m *WriteFileRequest) XXX_Size() int {
	return xxx_messageInfo_WriteFileRequest.Size(m)
}
func (m *WriteFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteFileRequest proto.InternalMessageInfo

func (m *WriteFileRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *WriteFileRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *WriteFileRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type WriteFileResponse struct {
	// Types that are valid to be assigned to Result:
	//	*WriteFileResponse_Written
	//	*WriteFileResponse_Error
	Result               isWriteFileResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *WriteFileResponse) Reset()         { *m = WriteFileResponse{} }
func (m *WriteFileResponse) String() string { return proto.CompactTextString(m) }
func (*WriteFileResponse) ProtoMessage()    {}
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{23}
}

func (m *WriteFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteFileResponse.Unmarshal(m, b)
}
func (m *WriteFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteFileResponse.Marshal(b, m, deterministic)
}
func (m *WriteFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteFileResponse.Merge(m, src)
}
func (m *WriteFileResponse) XXX_Size() int {
	return xxx_messageInfo_WriteFileResponse.Size(m)
}
func (m *WriteFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WriteFileResponse proto.InternalMessageInfo

type isWriteFileResponse_Result interface {
	isWriteFileResponse_Result()
}

type WriteFileResponse_Written struct {
	Written uint64 `protobuf:"varint,1,opt,name=written,proto3,oneof"`
}

type WriteFileResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*WriteFileResponse_Written) isWriteFileResponse_Result() {}

func (*WriteFileResponse_Error) isWriteFileResponse_Result() {}

func (m *WriteFileResponse) GetResult() isWriteFileResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *WriteFileResponse) GetWritten() uint64 {
	if x, ok := m.GetResult().(*WriteFileResponse_Written); ok {
		return x.Written
	}
	return 0
}

func (m *WriteFileResponse) GetError() *Error {
	if x, ok := m.GetResult().(*WriteFileResponse_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*WriteFileResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*WriteFileResponse_Written)(nil),
		(*WriteFileResponse_Error)(nil),
	}
}

type CloseFileRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseFileRequest) Reset()         { *m = CloseFileRequest{} }
func (m *CloseFileRequest) String() string { return proto.CompactTextString(m) }
func (*CloseFileRequest) ProtoMessage()    {}
func (*CloseFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{24}
}

func (m *CloseFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseFileRequest.Unmarshal(m, b)
}
func (m *CloseFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseFileRequest.Marshal(b, m, deterministic)
}
func (m *CloseFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseFileRequest.Merge(m, src)
}
func (m *CloseFileRequest) XXX_Size() int {
	return xxx_messageInfo_CloseFileRequest.Size(m)
}
func (m *CloseFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseFileRequest proto.InternalMessageInfo

func (m *CloseFileRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type CloseFileResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseFileResponse) Reset()         { *m = CloseFileResponse{} }
func (m *CloseFileResponse) String() string { return proto.CompactTextString(m) }
func (*CloseFileResponse) ProtoMessage()    {}
func (*CloseFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{25}
}

func (m *CloseFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseFileResponse.Unmarshal(m, b)
}
func (m *CloseFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseFileResponse.Marshal(b, m, deterministic)
}
func (m *CloseFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseFileResponse.Merge(m, src)
}
func (m *CloseFileResponse) XXX_Size() int {
	return xxx_messageInfo_CloseFileResponse.Size(m)
}
func (m *CloseFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloseFileResponse proto.InternalMessageInfo

func (m *CloseFileResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type SyncFileRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncFileRequest) Reset()         { *m = SyncFileRequest{} }
func (m *SyncFileRequest) String() string { return proto.CompactTextString(m) }
func (*SyncFileRequest) ProtoMessage()    {}
func (*SyncFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{26}
}

func (m *SyncFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncFileRequest.Unmarshal(m, b)
}
func (m *SyncFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncFileRequest.Marshal(b, m, deterministic)
}
func (m *SyncFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncFileRequest.Merge(m, src)
}
func (m *SyncFileRequest) XXX_Size() int {
	return xxx_messageInfo_SyncFileRequest.Size(m)
}
func (m *SyncFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncFileRequest proto.InternalMessageInfo

func (m *SyncFileRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *SyncFileRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *SyncFileRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SyncFileResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncFileResponse) Reset()         { *m = SyncFileResponse{} }
func (m *SyncFileResponse) String() string { return proto.CompactTextString(m) }
func (*SyncFileResponse) ProtoMessage()    {}
func (*SyncFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{27}
}

func (m *SyncFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncFileResponse.Unmarshal(m, b)
}
func (m *SyncFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncFileResponse.Marshal(b, m, deterministic)
}
func (m *SyncFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncFileResponse.Merge(m, src)
}
func (m *SyncFileResponse) XXX_Size() int {
	return xxx_messageInfo_SyncFileResponse.Size(m)
}
func (m *SyncFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SyncFileResponse proto.InternalMessageInfo

func (m *SyncFileResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type GetAttrRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAttrRequest) Reset()         { *m = GetAttrRequest{} }
func (m *GetAttrRequest) String() string { return proto.CompactTextString(m) }
func (*GetAttrRequest) ProtoMessage()    {}
func (*GetAttrRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{28}
}

func (m *GetAttrRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAttrRequest.Unmarshal(m, b)
}
func (m *GetAttrRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAttrRequest.Marshal(b, m, deterministic)
}
func (m *GetAttrRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAttrRequest.Merge(m, src)
}
func (m *GetAttrRequest) XXX_Size() int {
	return xxx_messageInfo_GetAttrRequest.Size(m)
}
func (m *GetAttrRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAttrRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAttrRequest proto.InternalMessageInfo

func (m *GetAttrRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type GetAttrResponse struct {
	// Types that are valid to be assigned to Result:
	//	*GetAttrResponse_Attr
	//	*GetAttrResponse_Error
	Result               isGetAttrResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetAttrResponse) Reset()         { *m = GetAttrResponse{} }
func (m *GetAttrResponse) String() string { return proto.CompactTextString(m) }
func (*GetAttrResponse) ProtoMessage()    {}
func (*GetAttrResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{29}
}

func (m *GetAttrResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAttrResponse.Unmarshal(m, b)
}
func (m *GetAttrResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAttrResponse.Marshal(b, m, deterministic)
}
func (m *GetAttrResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAttrResponse.Merge(m, src)
}
func (m *GetAttrResponse) XXX_Size() int {
	return xxx_messageInfo_GetAttrResponse.Size(m)
}
func (m *GetAttrResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAttrResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAttrResponse proto.InternalMessageInfo

type isGetAttrResponse_Result interface {
	isGetAttrResponse_Result()
}

type GetAttrResponse_Attr struct {
	Attr *Attr `protobuf:"bytes,1,opt,name=attr,proto3,oneof"`
}

type GetAttrResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetAttrResponse_Attr) isGetAttrResponse_Result() {}

func (*GetAttrResponse_Error) isGetAttrResponse_Result() {}

func (m *GetAttrResponse) GetResult() isGetAttrResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetAttrResponse) GetAttr() *Attr {
	if x, ok := m.GetResult().(*GetAttrResponse_Attr); ok {
		return x.Attr
	}
	return nil
}

func (m *GetAttrResponse) GetError() *Error {
	if x, ok := m.GetResult().(*GetAttrResponse_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetAttrResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetAttrResponse_Attr)(nil),
		(*GetAttrResponse_Error)(nil),
	}
}

type SetAttrRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Attr                 *Attr    `protobuf:"bytes,2,opt,name=attr,proto3" json:"attr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAttrRequest) Reset()         { *m = SetAttrRequest{} }
func (m *SetAttrRequest) String() string { return proto.CompactTextString(m) }
func (*SetAttrRequest) ProtoMessage()    {}
func (*SetAttrRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{30}
}

func (m *SetAttrRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAttrRequest.Unmarshal(m, b)
}
func (m *SetAttrRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAttrRequest.Marshal(b, m, deterministic)
}
func (m *SetAttrRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAttrRequest.Merge(m, src)
}
func (m *SetAttrRequest) XXX_Size() int {
	return xxx_messageInfo_SetAttrRequest.Size(m)
}
func (m *SetAttrRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAttrRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetAttrRequest proto.InternalMessageInfo

func (m *SetAttrRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *SetAttrRequest) GetAttr() *Attr {
	if m != nil {
		return m.Attr
	}
	return nil
}

type SetAttrResponse struct {
	// Types that are valid to be assigned to Result:
	//	*SetAttrResponse_Attr
	//	*SetAttrResponse_Error
	Result               isSetAttrResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *SetAttrResponse) Reset()         { *m = SetAttrResponse{} }
func (m *SetAttrResponse) String() string { return proto.CompactTextString(m) }
func (*SetAttrResponse) ProtoMessage()    {}
func (*SetAttrResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{31}
}

func (m *SetAttrResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAttrResponse.Unmarshal(m, b)
}
func (m *SetAttrResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAttrResponse.Marshal(b, m, deterministic)
}
func (m *SetAttrResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAttrResponse.Merge(m, src)
}
func (m *SetAttrResponse) XXX_Size() int {
	return xxx_messageInfo_SetAttrResponse.Size(m)
}
func (m *SetAttrResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAttrResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetAttrResponse proto.InternalMessageInfo

type isSetAttrResponse_Result interface {
	isSetAttrResponse_Result()
}

type SetAttrResponse_Attr struct {
	Attr *Attr `protobuf:"bytes,1,opt,name=attr,proto3,oneof"`
}

type SetAttrResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*SetAttrResponse_Attr) isSetAttrResponse_Result() {}

func (*SetAttrResponse_Error) isSetAttrResponse_Result() {}

func (m *SetAttrResponse) GetResult() isSetAttrResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *SetAttrResponse) GetAttr() *Attr {
	if x, ok := m.GetResult().(*SetAttrResponse_Attr); ok {
		return x.Attr
	}
	return nil
}

func (m *SetAttrResponse) GetError() *Error {
	if x, ok := m.GetResult().(*SetAttrResponse_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SetAttrResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SetAttrResponse_Attr)(nil),
		(*SetAttrResponse_Error)(nil),
	}
}

func init() {
	proto.RegisterEnum("rpc.EntryType", EntryType_name, EntryType_value)
	proto.RegisterType((*Error)(nil), "rpc.Error")
	proto.RegisterType((*Attr)(nil), "rpc.Attr")
	proto.RegisterType((*ReadDirRequest)(nil), "rpc.ReadDirRequest")
	proto.RegisterType((*ReadDirResponse)(nil), "rpc.ReadDirResponse")
	proto.RegisterType((*ReadDirResponse_DirEntry)(nil), "rpc.ReadDirResponse.DirEntry")
	proto.RegisterType((*LookupRequest)(nil), "rpc.LookupRequest")
	proto.RegisterType((*LookupResponse)(nil), "rpc.LookupResponse")
	proto.RegisterType((*MkdirRequest)(nil), "rpc.MkdirRequest")
	proto.RegisterType((*MkdirResponse)(nil), "rpc.MkdirResponse")
	proto.RegisterType((*CreateFileRequest)(nil), "rpc.CreateFileRequest")
	proto.RegisterType((*CreateFileResponse)(nil), "rpc.CreateFileResponse")
	proto.RegisterType((*UnlinkRequest)(nil), "rpc.UnlinkRequest")
	proto.RegisterType((*UnlinkResponse)(nil), "rpc.UnlinkResponse")
	proto.RegisterType((*RmDirRequest)(nil), "rpc.RmDirRequest")
	proto.RegisterType((*RmDirResponse)(nil), "rpc.RmDirResponse")
	proto.RegisterType((*RenameRequest)(nil), "rpc.RenameRequest")
	proto.RegisterType((*RenameResponse)(nil), "rpc.RenameResponse")
	proto.RegisterType((*OpenFileRequest)(nil), "rpc.OpenFileRequest")
	proto.RegisterType((*OpenFileResponse)(nil), "rpc.OpenFileResponse")
	proto.RegisterType((*AllocateRequest)(nil), "rpc.AllocateRequest")
	proto.RegisterType((*AllocateResponse)(nil), "rpc.AllocateResponse")
	proto.RegisterType((*ReadFileRequest)(nil), "rpc.ReadFileRequest")
	proto.RegisterType((*ReadFileResponse)(nil), "rpc.ReadFileResponse")
	proto.RegisterType((*WriteFileRequest)(nil), "rpc.WriteFileRequest")
	proto.RegisterType((*WriteFileResponse)(nil), "rpc.WriteFileResponse")
	proto.RegisterType((*CloseFileRequest)(nil), "rpc.CloseFileRequest")
	proto.RegisterType((*CloseFileResponse)(nil), "rpc.CloseFileResponse")
	proto.RegisterType((*SyncFileRequest)(nil), "rpc.SyncFileRequest")
	proto.RegisterType((*SyncFileResponse)(nil), "rpc.SyncFileResponse")
	proto.RegisterType((*GetAttrRequest)(nil), "rpc.GetAttrRequest")
	proto.RegisterType((*GetAttrResponse)(nil), "rpc.GetAttrResponse")
	proto.RegisterType((*SetAttrRequest)(nil), "rpc.SetAttrRequest")
	proto.RegisterType((*SetAttrResponse)(nil), "rpc.SetAttrResponse")
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor_2bc2336598a3f7e0) }

var fileDescriptor_2bc2336598a3f7e0 = []byte{
	// 1075 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x6d, 0x6f, 0x1b, 0x45,
	0x10, 0xf6, 0xe5, 0xce, 0xb1, 0x3d, 0x89, 0x1d, 0x77, 0x53, 0x8c, 0x75, 0xa8, 0xad, 0x75, 0x02,
	0x64, 0xf5, 0x83, 0x5b, 0xdc, 0x52, 0x89, 0x96, 0xb7, 0x36, 0x31, 0xe4, 0x03, 0x14, 0xba, 0x0e,
	0xe1, 0x13, 0x2f, 0x57, 0x7b, 0xed, 0x9c, 0x72, 0x77, 0x7b, 0xec, 0x6d, 0x14, 0x19, 0x89, 0x7f,
	0xc2, 0x2f, 0xe2, 0x07, 0xf0, 0x7b, 0xd0, 0xbe, 0xdc, 0xab, 0x9d, 0xd8, 0x51, 0xf1, 0xb7, 0xdd,
	0xd9, 0x79, 0x66, 0x9f, 0x9d, 0x99, 0x9d, 0x19, 0x68, 0x45, 0x8c, 0x72, 0x3a, 0xa1, 0xfe, 0x40,
	0x2e, 0x90, 0xc9, 0xa2, 0x89, 0xfd, 0x60, 0x4e, 0xe9, 0xdc, 0x27, 0x8f, 0xa4, 0xe8, 0xed, 0xe5,
	0xec, 0x11, 0xf7, 0x02, 0x12, 0x73, 0x37, 0x88, 0x94, 0x96, 0xfd, 0x41, 0x59, 0x81, 0x04, 0x11,
	0x5f, 0xa8, 0x43, 0xe7, 0x39, 0x54, 0x47, 0x8c, 0x51, 0x86, 0x3a, 0x50, 0x25, 0x8c, 0x85, 0xb4,
	0x6b, 0xf4, 0x8c, 0x7e, 0xf3, 0xa4, 0x82, 0xd5, 0x16, 0x21, 0x30, 0x83, 0x78, 0xde, 0xdd, 0xe9,
	0x19, 0xfd, 0xc6, 0x49, 0x05, 0x8b, 0xcd, 0xab, 0x2a, 0x98, 0x84, 0x31, 0xe7, 0xdf, 0x1d, 0xb0,
	0x5e, 0x72, 0xce, 0x10, 0x02, 0x2b, 0x74, 0x03, 0x22, 0xa1, 0x0d, 0x2c, 0xd7, 0x42, 0x16, 0xd0,
	0x29, 0x91, 0xc0, 0x2a, 0x96, 0x6b, 0x21, 0x8b, 0xbd, 0x3f, 0x49, 0xd7, 0xec, 0x19, 0x7d, 0x13,
	0xcb, 0x35, 0x72, 0xc0, 0xe2, 0x8b, 0x88, 0x74, 0xad, 0x9e, 0xd1, 0x6f, 0x0d, 0x5b, 0x03, 0x16,
	0x4d, 0x06, 0xa3, 0x90, 0xb3, 0xc5, 0xe9, 0x22, 0x22, 0x58, 0x9e, 0xa1, 0xe7, 0x00, 0xee, 0x64,
	0x42, 0xe2, 0xf8, 0xd4, 0x0b, 0x48, 0xb7, 0xda, 0x33, 0xfa, 0x7b, 0x43, 0x7b, 0xa0, 0x9e, 0x35,
	0x48, 0x9e, 0x35, 0x38, 0x4d, 0xde, 0x8d, 0x73, 0xda, 0x02, 0x1b, 0xd0, 0xa9, 0x37, 0x5b, 0x48,
	0xec, 0xee, 0x7a, 0x6c, 0xa6, 0x2d, 0xb0, 0x93, 0x73, 0x37, 0x9c, 0x13, 0x89, 0xad, 0xad, 0xc7,
	0x66, 0xda, 0x12, 0xcb, 0x88, 0xcb, 0x15, 0xb6, 0xbe, 0x01, 0x36, 0xd5, 0x76, 0x1e, 0x42, 0x0b,
	0x13, 0x77, 0x7a, 0xec, 0x31, 0x4c, 0xfe, 0xb8, 0x24, 0x31, 0x47, 0x5d, 0xa8, 0x4d, 0x3d, 0xf6,
	0xa3, 0xcb, 0xcf, 0xb5, 0x93, 0x93, 0xad, 0xf3, 0x8f, 0x01, 0x07, 0xa9, 0x72, 0x1c, 0xd1, 0x30,
	0x26, 0xe8, 0x0b, 0x80, 0xa9, 0xc7, 0x84, 0x17, 0x3d, 0x12, 0x77, 0x8d, 0x9e, 0xd9, 0xdf, 0x1b,
	0xde, 0x93, 0x9e, 0x2d, 0x69, 0x0e, 0x8e, 0x95, 0xda, 0x02, 0xe7, 0x00, 0xa8, 0x27, 0x53, 0x81,
	0x32, 0x19, 0xbb, 0xbd, 0x21, 0xa8, 0x98, 0x08, 0x09, 0x56, 0x07, 0xf6, 0x19, 0xd4, 0x13, 0xe4,
	0xca, 0xe0, 0x27, 0x41, 0xdd, 0xb9, 0x21, 0xa8, 0x49, 0x82, 0x88, 0x64, 0x68, 0xaa, 0x04, 0x71,
	0x46, 0xd0, 0xfc, 0x8e, 0xd2, 0x8b, 0xcb, 0x68, 0xed, 0xbb, 0x91, 0x0d, 0xf5, 0x99, 0xe7, 0x13,
	0x79, 0xb5, 0x4c, 0x4e, 0x9c, 0xee, 0x9d, 0xdf, 0xa0, 0x95, 0x98, 0xd1, 0x1e, 0x79, 0x00, 0x96,
	0xcb, 0x39, 0x93, 0x46, 0xf6, 0x86, 0x0d, 0x49, 0x48, 0xa4, 0xee, 0x49, 0x05, 0xcb, 0x03, 0xe4,
	0x5c, 0xfb, 0x66, 0xfd, 0x15, 0x28, 0x7b, 0x55, 0x87, 0x5d, 0x46, 0xe2, 0x4b, 0x9f, 0x3b, 0x67,
	0xb0, 0xff, 0xfd, 0xc5, 0x74, 0x83, 0xf0, 0x88, 0x93, 0x90, 0x5c, 0xbd, 0xce, 0x58, 0x26, 0xdb,
	0x95, 0xef, 0xff, 0x15, 0x9a, 0xda, 0xee, 0x76, 0x78, 0xff, 0x02, 0x77, 0x8e, 0x64, 0x9a, 0x7d,
	0xe3, 0xf9, 0xe4, 0x9d, 0x7c, 0xbc, 0x92, 0xfe, 0x04, 0x50, 0xde, 0xfc, 0x76, 0xde, 0x30, 0x82,
	0xe6, 0x4f, 0xa1, 0xef, 0x85, 0x17, 0xef, 0x96, 0x23, 0x43, 0x68, 0x25, 0x66, 0x34, 0xcf, 0x34,
	0xed, 0x8d, 0x6b, 0xd2, 0xde, 0xf9, 0x1a, 0xf6, 0x71, 0xb0, 0xc9, 0xaf, 0x44, 0x1d, 0xd8, 0x65,
	0x41, 0x2e, 0xea, 0x7a, 0xe7, 0x7c, 0x02, 0x4d, 0x6d, 0x61, 0xe3, 0x4b, 0xff, 0x82, 0x26, 0x96,
	0x94, 0x37, 0x4a, 0x36, 0xea, 0x4f, 0xf3, 0xc9, 0xa6, 0xb7, 0xe8, 0x3e, 0x40, 0x48, 0xae, 0x8e,
	0x35, 0xcc, 0x94, 0x87, 0x39, 0x49, 0x3e, 0x4d, 0xad, 0x42, 0x9a, 0x0a, 0x3f, 0x25, 0xd7, 0x6f,
	0x4c, 0xf9, 0x23, 0x38, 0xf8, 0x21, 0x22, 0x61, 0x3e, 0xc9, 0x10, 0x58, 0x51, 0xc6, 0x58, 0xae,
	0x1d, 0x17, 0xda, 0x99, 0xda, 0x76, 0x92, 0xe5, 0x0d, 0x1c, 0xbc, 0xf4, 0x7d, 0x3a, 0x71, 0xf9,
	0x4d, 0x4c, 0x44, 0xb8, 0xe8, 0x6c, 0x16, 0x13, 0x2e, 0x5d, 0x63, 0x61, 0xbd, 0x4b, 0x1b, 0x96,
	0x25, 0xa5, 0x72, 0xed, 0x3c, 0x85, 0x76, 0x66, 0x72, 0x63, 0x97, 0xbc, 0x51, 0x55, 0x7a, 0x8d,
	0x4b, 0x72, 0x44, 0x76, 0x56, 0x12, 0x31, 0x73, 0x44, 0xce, 0xa0, 0x9d, 0x99, 0xd4, 0x44, 0xee,
	0x82, 0x35, 0x75, 0xb9, 0x2b, 0x6d, 0xee, 0x0b, 0x9f, 0x89, 0xdd, 0x2d, 0x7d, 0x86, 0xa1, 0xfd,
	0x33, 0xf3, 0x8a, 0x35, 0xe2, 0x96, 0x5c, 0x25, 0x07, 0xc1, 0x75, 0x5f, 0x31, 0x10, 0x85, 0x27,
	0x67, 0x53, 0x93, 0xb5, 0xa1, 0x76, 0xc5, 0x3c, 0xce, 0x49, 0x28, 0xed, 0x5a, 0x27, 0x15, 0x9c,
	0x08, 0x6e, 0x49, 0xf9, 0x63, 0x68, 0x1f, 0xf9, 0x34, 0x5e, 0x47, 0xd9, 0xf9, 0x14, 0xee, 0xe4,
	0xf4, 0x6e, 0x13, 0xbc, 0xf1, 0x22, 0x9c, 0xfc, 0x9f, 0x0e, 0x79, 0x0a, 0xed, 0xcc, 0xe4, 0xc6,
	0x44, 0x3e, 0x84, 0xd6, 0xb7, 0x84, 0x8b, 0xff, 0x70, 0xd3, 0x2b, 0x7f, 0x87, 0x83, 0x54, 0x6b,
	0x3b, 0xdf, 0xea, 0x08, 0x5a, 0xe3, 0xb5, 0x3c, 0xd0, 0x3d, 0x7d, 0xe9, 0x4e, 0xe9, 0x52, 0x75,
	0xa5, 0xa0, 0x39, 0xde, 0x2a, 0xcd, 0x87, 0xf7, 0xa1, 0x91, 0x4e, 0x1d, 0xa8, 0x0e, 0x96, 0x28,
	0xfe, 0xed, 0x0a, 0xaa, 0x81, 0x39, 0xf5, 0x58, 0xdb, 0x18, 0xfe, 0x5d, 0x03, 0xf3, 0x74, 0x16,
	0xa3, 0x17, 0x50, 0x7b, 0x4d, 0xf9, 0xb9, 0x17, 0xce, 0x51, 0x67, 0x69, 0x44, 0x1b, 0x89, 0x69,
	0xd9, 0xbe, 0x46, 0xee, 0x54, 0xd0, 0x33, 0xa8, 0xe9, 0xa9, 0x0a, 0x1d, 0x16, 0x67, 0x2c, 0xe9,
	0x19, 0xfb, 0xee, 0xaa, 0xc1, 0xcb, 0xa9, 0xa0, 0x27, 0xb0, 0xab, 0x86, 0x14, 0x84, 0xa4, 0x46,
	0x61, 0xf0, 0xb1, 0x0f, 0x0b, 0xb2, 0x14, 0xf4, 0x18, 0xaa, 0x72, 0x40, 0x40, 0x77, 0xe4, 0x79,
	0x7e, 0x08, 0xb1, 0x51, 0x5e, 0x94, 0x22, 0xbe, 0x02, 0xc8, 0x7a, 0x32, 0xea, 0x48, 0x9d, 0xa5,
	0x19, 0xc0, 0x7e, 0x7f, 0x49, 0x9e, 0xe7, 0xa9, 0x1a, 0xa5, 0xe6, 0x59, 0x68, 0xbe, 0x9a, 0x67,
	0xb1, 0x93, 0x2a, 0x9e, 0xb2, 0xcf, 0x69, 0x9e, 0xf9, 0xae, 0xa9, 0x79, 0x16, 0xda, 0xa0, 0xba,
	0x06, 0xeb, 0xc9, 0x42, 0x3b, 0x2c, 0xd7, 0xf3, 0xec, 0xc3, 0x82, 0x2c, 0x05, 0x7d, 0x06, 0xf5,
	0xa4, 0x83, 0x20, 0xe5, 0xe7, 0x52, 0xdf, 0xb1, 0xdf, 0x2b, 0x49, 0xf3, 0xd0, 0xa4, 0x8c, 0x6b,
	0x68, 0xa9, 0x51, 0x68, 0x68, 0xb9, 0xd6, 0x3b, 0x15, 0xf4, 0x02, 0xea, 0x49, 0xe1, 0x45, 0x59,
	0x74, 0x97, 0x6f, 0x2d, 0x57, 0x67, 0xa7, 0xf2, 0xd8, 0x40, 0x5f, 0x42, 0x23, 0xad, 0x84, 0x48,
	0xe9, 0x95, 0xab, 0xad, 0xdd, 0x29, 0x8b, 0x13, 0x7c, 0xdf, 0x40, 0x9f, 0x43, 0x23, 0x2d, 0x61,
	0x1a, 0x5f, 0x2e, 0x7d, 0x1a, 0xbf, 0x54, 0xe9, 0x14, 0xf5, 0xa4, 0xec, 0x68, 0xea, 0xa5, 0xc2,
	0xa6, 0xa9, 0x97, 0x6b, 0x93, 0xbc, 0xfa, 0x19, 0xd4, 0x74, 0x5d, 0xd1, 0x99, 0x5e, 0xac, 0x45,
	0x3a, 0xd3, 0x4b, 0xa5, 0x47, 0xfd, 0x90, 0x71, 0x01, 0x37, 0x5e, 0x85, 0x1b, 0x97, 0x71, 0x6f,
	0x77, 0xe5, 0x5f, 0x7b, 0xf2, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x1c, 0xaf, 0x74, 0xf7,
	0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TfsClient is the client API for Tfs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TfsClient interface {
	// speed test
	Nothing(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	// dir
	ReadDir(ctx context.Context, in *ReadDirRequest, opts ...grpc.CallOption) (*ReadDirResponse, error)
	Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error)
	Mkdir(ctx context.Context, in *MkdirRequest, opts ...grpc.CallOption) (*MkdirResponse, error)
	CreateFile(ctx context.Context, in *CreateFileRequest, opts ...grpc.CallOption) (*CreateFileResponse, error)
	Unlink(ctx context.Context, in *UnlinkRequest, opts ...grpc.CallOption) (*UnlinkResponse, error)
	RmDir(ctx context.Context, in *RmDirRequest, opts ...grpc.CallOption) (*RmDirResponse, error)
	Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*RenameResponse, error)
	// file
	OpenFile(ctx context.Context, in *OpenFileRequest, opts ...grpc.CallOption) (*OpenFileResponse, error)
	Allocate(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*AllocateResponse, error)
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (Tfs_ReadFileClient, error)
	WriteFile(ctx context.Context, opts ...grpc.CallOption) (Tfs_WriteFileClient, error)
	CloseFile(ctx context.Context, in *CloseFileRequest, opts ...grpc.CallOption) (*CloseFileResponse, error)
	SyncFile(ctx context.Context, opts ...grpc.CallOption) (Tfs_SyncFileClient, error)
	// normal
	GetAttr(ctx context.Context, in *GetAttrRequest, opts ...grpc.CallOption) (*GetAttrResponse, error)
	SetAttr(ctx context.Context, in *SetAttrRequest, opts ...grpc.CallOption) (*SetAttrResponse, error)
}

type tfsClient struct {
	cc *grpc.ClientConn
}

func NewTfsClient(cc *grpc.ClientConn) TfsClient {
	return &tfsClient{cc}
}

func (c *tfsClient) Nothing(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/rpc.Tfs/Nothing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tfsClient) ReadDir(ctx context.Context, in *ReadDirRequest, opts ...grpc.CallOption) (*ReadDirResponse, error) {
	out := new(ReadDirResponse)
	err := c.cc.Invoke(ctx, "/rpc.Tfs/ReadDir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tfsClient) Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error) {
	out := new(LookupResponse)
	err := c.cc.Invoke(ctx, "/rpc.Tfs/Lookup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tfsClient) Mkdir(ctx context.Context, in *MkdirRequest, opts ...grpc.CallOption) (*MkdirResponse, error) {
	out := new(MkdirResponse)
	err := c.cc.Invoke(ctx, "/rpc.Tfs/Mkdir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tfsClient) CreateFile(ctx context.Context, in *CreateFileRequest, opts ...grpc.CallOption) (*CreateFileResponse, error) {
	out := new(CreateFileResponse)
	err := c.cc.Invoke(ctx, "/rpc.Tfs/CreateFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tfsClient) Unlink(ctx context.Context, in *UnlinkRequest, opts ...grpc.CallOption) (*UnlinkResponse, error) {
	out := new(UnlinkResponse)
	err := c.cc.Invoke(ctx, "/rpc.Tfs/Unlink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tfsClient) RmDir(ctx context.Context, in *RmDirRequest, opts ...grpc.CallOption) (*RmDirResponse, error) {
	out := new(RmDirResponse)
	err := c.cc.Invoke(ctx, "/rpc.Tfs/RmDir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tfsClient) Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*RenameResponse, error) {
	out := new(RenameResponse)
	err := c.cc.Invoke(ctx, "/rpc.Tfs/Rename", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tfsClient) OpenFile(ctx context.Context, in *OpenFileRequest, opts ...grpc.CallOption) (*OpenFileResponse, error) {
	out := new(OpenFileResponse)
	err := c.cc.Invoke(ctx, "/rpc.Tfs/OpenFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tfsClient) Allocate(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*AllocateResponse, error) {
	out := new(AllocateResponse)
	err := c.cc.Invoke(ctx, "/rpc.Tfs/Allocate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tfsClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (Tfs_ReadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Tfs_serviceDesc.Streams[0], "/rpc.Tfs/ReadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &tfsReadFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Tfs_ReadFileClient interface {
	Recv() (*ReadFileResponse, error)
	grpc.ClientStream
}

type tfsReadFileClient struct {
	grpc.ClientStream
}

func (x *tfsReadFileClient) Recv() (*ReadFileResponse, error) {
	m := new(ReadFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tfsClient) WriteFile(ctx context.Context, opts ...grpc.CallOption) (Tfs_WriteFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Tfs_serviceDesc.Streams[1], "/rpc.Tfs/WriteFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &tfsWriteFileClient{stream}
	return x, nil
}

type Tfs_WriteFileClient interface {
	Send(*WriteFileRequest) error
	CloseAndRecv() (*WriteFileResponse, error)
	grpc.ClientStream
}

type tfsWriteFileClient struct {
	grpc.ClientStream
}

func (x *tfsWriteFileClient) Send(m *WriteFileRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tfsWriteFileClient) CloseAndRecv() (*WriteFileResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(WriteFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tfsClient) CloseFile(ctx context.Context, in *CloseFileRequest, opts ...grpc.CallOption) (*CloseFileResponse, error) {
	out := new(CloseFileResponse)
	err := c.cc.Invoke(ctx, "/rpc.Tfs/CloseFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tfsClient) SyncFile(ctx context.Context, opts ...grpc.CallOption) (Tfs_SyncFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Tfs_serviceDesc.Streams[2], "/rpc.Tfs/SyncFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &tfsSyncFileClient{stream}
	return x, nil
}

type Tfs_SyncFileClient interface {
	Send(*SyncFileRequest) error
	CloseAndRecv() (*SyncFileResponse, error)
	grpc.ClientStream
}

type tfsSyncFileClient struct {
	grpc.ClientStream
}

func (x *tfsSyncFileClient) Send(m *SyncFileRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tfsSyncFileClient) CloseAndRecv() (*SyncFileResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SyncFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tfsClient) GetAttr(ctx context.Context, in *GetAttrRequest, opts ...grpc.CallOption) (*GetAttrResponse, error) {
	out := new(GetAttrResponse)
	err := c.cc.Invoke(ctx, "/rpc.Tfs/GetAttr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tfsClient) SetAttr(ctx context.Context, in *SetAttrRequest, opts ...grpc.CallOption) (*SetAttrResponse, error) {
	out := new(SetAttrResponse)
	err := c.cc.Invoke(ctx, "/rpc.Tfs/SetAttr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TfsServer is the server API for Tfs service.
type TfsServer interface {
	// speed test
	Nothing(context.Context, *empty.Empty) (*empty.Empty, error)
	// dir
	ReadDir(context.Context, *ReadDirRequest) (*ReadDirResponse, error)
	Lookup(context.Context, *LookupRequest) (*LookupResponse, error)
	Mkdir(context.Context, *MkdirRequest) (*MkdirResponse, error)
	CreateFile(context.Context, *CreateFileRequest) (*CreateFileResponse, error)
	Unlink(context.Context, *UnlinkRequest) (*UnlinkResponse, error)
	RmDir(context.Context, *RmDirRequest) (*RmDirResponse, error)
	Rename(context.Context, *RenameRequest) (*RenameResponse, error)
	// file
	OpenFile(context.Context, *OpenFileRequest) (*OpenFileResponse, error)
	Allocate(context.Context, *AllocateRequest) (*AllocateResponse, error)
	ReadFile(*ReadFileRequest, Tfs_ReadFileServer) error
	WriteFile(Tfs_WriteFileServer) error
	CloseFile(context.Context, *CloseFileRequest) (*CloseFileResponse, error)
	SyncFile(Tfs_SyncFileServer) error
	// normal
	GetAttr(context.Context, *GetAttrRequest) (*GetAttrResponse, error)
	SetAttr(context.Context, *SetAttrRequest) (*SetAttrResponse, error)
}

// UnimplementedTfsServer can be embedded to have forward compatible implementations.
type UnimplementedTfsServer struct {
}

func (*UnimplementedTfsServer) Nothing(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Nothing not implemented")
}
func (*UnimplementedTfsServer) ReadDir(ctx context.Context, req *ReadDirRequest) (*ReadDirResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadDir not implemented")
}
func (*UnimplementedTfsServer) Lookup(ctx context.Context, req *LookupRequest) (*LookupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lookup not implemented")
}
func (*UnimplementedTfsServer) Mkdir(ctx context.Context, req *MkdirRequest) (*MkdirResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mkdir not implemented")
}
func (*UnimplementedTfsServer) CreateFile(ctx context.Context, req *CreateFileRequest) (*CreateFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFile not implemented")
}
func (*UnimplementedTfsServer) Unlink(ctx context.Context, req *UnlinkRequest) (*UnlinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unlink not implemented")
}
func (*UnimplementedTfsServer) RmDir(ctx context.Context, req *RmDirRequest) (*RmDirResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RmDir not implemented")
}
func (*UnimplementedTfsServer) Rename(ctx context.Context, req *RenameRequest) (*RenameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rename not implemented")
}
func (*UnimplementedTfsServer) OpenFile(ctx context.Context, req *OpenFileRequest) (*OpenFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenFile not implemented")
}
func (*UnimplementedTfsServer) Allocate(ctx context.Context, req *AllocateRequest) (*AllocateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Allocate not implemented")
}
func (*UnimplementedTfsServer) ReadFile(req *ReadFileRequest, srv Tfs_ReadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method ReadFile not implemented")
}
func (*UnimplementedTfsServer) WriteFile(srv Tfs_WriteFileServer) error {
	return status.Errorf(codes.Unimplemented, "method WriteFile not implemented")
}
func (*UnimplementedTfsServer) CloseFile(ctx context.Context, req *CloseFileRequest) (*CloseFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseFile not implemented")
}
func (*UnimplementedTfsServer) SyncFile(srv Tfs_SyncFileServer) error {
	return status.Errorf(codes.Unimplemented, "method SyncFile not implemented")
}
func (*UnimplementedTfsServer) GetAttr(ctx context.Context, req *GetAttrRequest) (*GetAttrResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttr not implemented")
}
func (*UnimplementedTfsServer) SetAttr(ctx context.Context, req *SetAttrRequest) (*SetAttrResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAttr not implemented")
}

func RegisterTfsServer(s *grpc.Server, srv TfsServer) {
	s.RegisterService(&_Tfs_serviceDesc, srv)
}

func _Tfs_Nothing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TfsServer).Nothing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Tfs/Nothing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TfsServer).Nothing(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tfs_ReadDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TfsServer).ReadDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Tfs/ReadDir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TfsServer).ReadDir(ctx, req.(*ReadDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tfs_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TfsServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Tfs/Lookup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TfsServer).Lookup(ctx, req.(*LookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tfs_Mkdir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MkdirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TfsServer).Mkdir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Tfs/Mkdir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TfsServer).Mkdir(ctx, req.(*MkdirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tfs_CreateFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TfsServer).CreateFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Tfs/CreateFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TfsServer).CreateFile(ctx, req.(*CreateFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tfs_Unlink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TfsServer).Unlink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Tfs/Unlink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TfsServer).Unlink(ctx, req.(*UnlinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tfs_RmDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RmDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TfsServer).RmDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Tfs/RmDir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TfsServer).RmDir(ctx, req.(*RmDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tfs_Rename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TfsServer).Rename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Tfs/Rename",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TfsServer).Rename(ctx, req.(*RenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tfs_OpenFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TfsServer).OpenFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Tfs/OpenFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TfsServer).OpenFile(ctx, req.(*OpenFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tfs_Allocate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TfsServer).Allocate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Tfs/Allocate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TfsServer).Allocate(ctx, req.(*AllocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tfs_ReadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TfsServer).ReadFile(m, &tfsReadFileServer{stream})
}

type Tfs_ReadFileServer interface {
	Send(*ReadFileResponse) error
	grpc.ServerStream
}

type tfsReadFileServer struct {
	grpc.ServerStream
}

func (x *tfsReadFileServer) Send(m *ReadFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Tfs_WriteFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TfsServer).WriteFile(&tfsWriteFileServer{stream})
}

type Tfs_WriteFileServer interface {
	SendAndClose(*WriteFileResponse) error
	Recv() (*WriteFileRequest, error)
	grpc.ServerStream
}

type tfsWriteFileServer struct {
	grpc.ServerStream
}

func (x *tfsWriteFileServer) SendAndClose(m *WriteFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tfsWriteFileServer) Recv() (*WriteFileRequest, error) {
	m := new(WriteFileRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Tfs_CloseFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TfsServer).CloseFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Tfs/CloseFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TfsServer).CloseFile(ctx, req.(*CloseFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tfs_SyncFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TfsServer).SyncFile(&tfsSyncFileServer{stream})
}

type Tfs_SyncFileServer interface {
	SendAndClose(*SyncFileResponse) error
	Recv() (*SyncFileRequest, error)
	grpc.ServerStream
}

type tfsSyncFileServer struct {
	grpc.ServerStream
}

func (x *tfsSyncFileServer) SendAndClose(m *SyncFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tfsSyncFileServer) Recv() (*SyncFileRequest, error) {
	m := new(SyncFileRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Tfs_GetAttr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TfsServer).GetAttr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Tfs/GetAttr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TfsServer).GetAttr(ctx, req.(*GetAttrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tfs_SetAttr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAttrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TfsServer).SetAttr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Tfs/SetAttr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TfsServer).SetAttr(ctx, req.(*SetAttrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tfs_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Tfs",
	HandlerType: (*TfsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Nothing",
			Handler:    _Tfs_Nothing_Handler,
		},
		{
			MethodName: "ReadDir",
			Handler:    _Tfs_ReadDir_Handler,
		},
		{
			MethodName: "Lookup",
			Handler:    _Tfs_Lookup_Handler,
		},
		{
			MethodName: "Mkdir",
			Handler:    _Tfs_Mkdir_Handler,
		},
		{
			MethodName: "CreateFile",
			Handler:    _Tfs_CreateFile_Handler,
		},
		{
			MethodName: "Unlink",
			Handler:    _Tfs_Unlink_Handler,
		},
		{
			MethodName: "RmDir",
			Handler:    _Tfs_RmDir_Handler,
		},
		{
			MethodName: "Rename",
			Handler:    _Tfs_Rename_Handler,
		},
		{
			MethodName: "OpenFile",
			Handler:    _Tfs_OpenFile_Handler,
		},
		{
			MethodName: "Allocate",
			Handler:    _Tfs_Allocate_Handler,
		},
		{
			MethodName: "CloseFile",
			Handler:    _Tfs_CloseFile_Handler,
		},
		{
			MethodName: "GetAttr",
			Handler:    _Tfs_GetAttr_Handler,
		},
		{
			MethodName: "SetAttr",
			Handler:    _Tfs_SetAttr_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadFile",
			Handler:       _Tfs_ReadFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WriteFile",
			Handler:       _Tfs_WriteFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SyncFile",
			Handler:       _Tfs_SyncFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "protocol.proto",
}
